name: njsscan json

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 18 * * 4'

permissions:
  contents: read

jobs:
  njsscan:
    permissions:
      contents: read # для использования actions/checkout для получения кода
      actions: read   # только для приватных репозиториев для github/codeql-action/upload-sarif для получения статуса действия
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
      with:
        args: '. --json --output results.json || true'  # Здесь меняем на формат JSON
    - name: Upload njsscan JSON report as artifact
      uses: actions/upload-artifact@v4  # Используем v3 для загрузки артефакта
      with:
        name: njsscan-json-report    # Имя артефакта
        path: results.json           # Путь к файлу отчета в формате JSON
